### ISSUE TITLE
Update conditions for publish-release.yml

### ISSUE THREAD

**Issue by schalkneethling** [mdn/workflows#44]
For each step where a condition is used, we need to repeat the entire conditional so:

```yml
  - uses: actions/checkout@v3
    if: '${{ inputs.npm-publish }}' && '${{ steps.release.outputs.release_created }}'
  - uses: actions/setup-node@v3
    with:
      node-version: '${{ inputs.node-version }}'
      registry-url: '${{ inputs.registry-url }}'
    if: '${{ inputs.npm-publish }}' && '${{ steps.release.outputs.release_created }}'
  - run: yarn install --frozen-lockfile
    if: '${{ inputs.npm-publish }}' && '${{ steps.release.outputs.release_created }}'
  - run: 'npm publish ${{ inputs.npm-publish-args }}'
    env:
      NODE_AUTH_TOKEN: '${{secrets.NPM_AUTH_TOKEN}}'
    if: '${{ inputs.npm-publish }}' && '${{ steps.release.outputs.release_created }}'
```
